[package]
name = "prusa_level"
version = "0.1.0"
authors = ["Joe Rozner <joe@deadbytes.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.7"
prettytable-rs = "^0.10"
